### ISSUE TITLE
drag/drop through uploaded files to reorder them

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonists/multiuploadfield#13]
that would be a nice feature.
last week i faced a paralax plugin with 3 overlapping photos, with their z-index in ascending order.

the solution was to upload them in proper order;

**Comment by pixelninja** [comment]
+1 this would be an insanely awesome enhancement. It would send it over the edge of awesomeness.

**Comment by brendo** [comment]
You can thank @orinocai as this has been implemented on `integration` :)

**Comment by pixelninja** [comment]
Fan-bloody-tastic! I'll give it a whirl later today. Epic stuff.

**Comment by pixelninja** [comment]
Couldn't wait, had to check it out now. Works like a charm, excellent feature.

**Comment by animaux** [comment]
Wow, brilliant!

**Comment by cmnstmntmn** [comment]
yeap, that's :+1:

**Comment by nitriques** [comment]
@brendo should we release it ?

**Comment by pixelninja** [comment]
I've been using it for a few months now, no bugs to report.

**Comment by nitriques** [comment]
Released! https://github.com/symphonists/multiuploadfield/releases/tag/1.6.0
