### ISSUE TITLE
2.6.0 - Class 'Symphony' not found

### ISSUE THREAD

**Issue by johnpuddephatt** [symphonists/multiuploadfield#22]
Adding a new file generates an "upload failed" message in the field UI.

Looking at the Network tab in Chrome's devtools, I can see the request to `upload.php?field-id=10&entry-id=3` results in the following response:
> Fatal error: Class 'Symphony' not found in [...]/symphony/lib/boot/bundle.php on line 18

(where [...] is the correct DOCROOT)

From looking at the request payload it looks like the file information is being submitted as a FormData object as expected. 

The [issue raised here](https://github.com/symphonycms/symphony-2/issues/2362) reports the same error, sounds like that was caused by using an older version of JIT or the S3 upload field. In that issue @Brendo asked if autoload.php/index.php were looking ok – I've checked and they are (this was a fresh install of the 2.6.0 beta, upgraded to 2.6.0 proper.)

**Comment by zooshme** [comment]
I'm encountering the same issue with Symphony 2.6.1

**Comment by brendo** [comment]
@zooshme @johnpuddephatt Give the `integration` branch a shot, if it works for you I'll release to `master`.

**Comment by johnpuddephatt** [comment]
All good! :shipit:

**Comment by nitriques** [comment]
Closing since it has been solved.
