### ISSUE TITLE
Upload failed on 2.6.1

### ISSUE THREAD

**Issue by Manaus** [symphonists/multiuploadfield#25]
Hello, I'm having some Internal Server errors while uploading images on the local host. I get not further info, just a red background beneath the files, so if you can tell how I can help...

**Comment by nitriques** [comment]
Can you try the integration branch please ? 

https://github.com/symphonists/multiuploadfield/tree/integration

**Comment by Manaus** [comment]
Works perfectly, thanks!

**Comment by brendo** [comment]
@nitriques Is there any reason to not merge `integration` onto `master`? Is it totally working 2.6?

**Comment by Manaus** [comment]
@brendo I see still a glitch in the thumbnails display on the article list
![2015-04-17 09 28 54 am](https://cloud.githubusercontent.com/assets/1131505/7197708/6290a40e-e4e4-11e4-81b8-4809d32109bb.png)
The code for the image is 

     ﻿<img src="http://localhost/architects/image/1/104/0/0//uploadsimg_3004.jpg">

**Comment by nitriques** [comment]
> Is there any reason to not merge integration onto master? 

I do not think so, except that I do not use this extension...

> Is it totally working 2.6?

Looks like it!

**Comment by nitriques** [comment]
@brendo see #23
