### ISSUE TITLE
Question: how would a frontend-form would have to look like …

### ISSUE THREAD

**Issue by animaux** [symphonists/multiuploadfield#26]
… to upload files from the frontend? Is this even possible? Would I be able to reuse code from the extension itself?

Thanks for any hints or pointers :)

**Comment by animaux** [comment]
`<input name="fields[bilder]" type="hidden" value="…" />`

I guess this is the default form preview in the event. Not very enlightening in  this case.

**Comment by brendo** [comment]
`<input name="fields[bilder][]" type="hidden" value="…" />` should do it functionality wise. As for the UI, I guess if you mimic the markup exactly you could reuse that as well?

**Comment by animaux** [comment]
Ok thanks, I’m beginning to understand (I think). Will investigate!

**Comment by nitriques** [comment]
Merged with https://github.com/symphonists/multiuploadfield/releases/tag/1.6.0
