### ISSUE TITLE
Multi upload field not showing in the datasource xml

### ISSUE THREAD

**Issue by zooshme** [symphonists/multiuploadfield#31]
I am using Symphony 2.6.1and the multi upload field extension. The the field is not showing up in the databasource xml although the field is selected in the visual editor. Any idea what I could be doing wrong?

**Comment by nitriques** [comment]
Can you post the actual content of the data source php file please ?

**Comment by nitriques** [comment]
Can you try the latest version: https://github.com/symphonists/multiuploadfield/releases/tag/1.6.0 ?

**Comment by nitriques** [comment]
This will be closed if no feedback in 4 days.
