### ISSUE TITLE
Cannot upload and save when trying to do multiple files

### ISSUE THREAD

**Issue by erichgoldman** [symphonists/multiuploadfield#33]
I received the following error trying to upload some images using multiple this. If I just upload one file, no problem.

I am on Symphony version: `Symphony 2.6.7`
PHP Version `PHP Version 5.5.35`

> Symphony Warning: mb_strlen() expects parameter 1 to be string, array given
> An error occurred in /[myserver]/symphony/lib/toolkit/class.general.php around line 402
> 
> 397 \* the string's length
> 398 */
> 399 public static function strlen($str)
> 400 {
> 401 if (function_exists('mb_strlen')) {
> 402 return mb_strlen($str, 'utf-8');
> 403 }
> 404 return strlen($str);
> 405 }
> 406

**Comment by nitriques** [comment]
Could you post the complete stack please ? Thanks!

**Comment by nitriques** [comment]
Ping!

**Comment by erichgoldman** [comment]
I can provide more details, is there a specific set or function you want me to run?

**Comment by nitriques** [comment]
Juste the complete stack of the crash (which function called which other...)

**Comment by erichgoldman** [comment]
I will try to find some time this weekend to reinstall and replicate.

**Comment by nitriques** [comment]
Ok thanks.

**Comment by erichgoldman** [comment]
Symphony Warning: mb_strlen() expects parameter 1 to be string, array given
```
An error occurred in /[myserver]/symphony/lib/toolkit/class.general.php around line 402
397 * the string's length
398 */
399 public static function strlen($str)
400 {
401 if (function_exists('mb_strlen')) {
402 return mb_strlen($str, 'utf-8');
403 }
404 return strlen($str);
405 }
406
```
Backtrace
```
[:0]
    GenericErrorHandler::handler();
[/[myserver]/symphony/lib/toolkit/class.general.php:402]
    mb_strlen();
[/[myserver]/symphony/lib/toolkit/class.field.php:999]
    General::strlen();
[/[myserver]/symphony/content/content.publish.php:1257]
    Field->prepareReadableValue();
[/[myserver]/symphony/content/content.publish.php:344]
    contentPublish->__viewEdit();
[/[myserver]/symphony/content/content.publish.php:349]
    contentPublish->__switchboard();
[/[myserver]/symphony/lib/toolkit/class.administrationpage.php:464]
    contentPublish->view();
[/[myserver]/symphony/content/content.publish.php:315]
    AdministrationPage->build();
[/[myserver]/symphony/lib/core/class.administration.php:212]
    contentPublish->build();
[/[myserver]/symphony/lib/core/class.administration.php:490]
    Administration->__buildPage();
[/[myserver]/symphony/lib/boot/func.utilities.php:231]
    Administration->display();
[/[myserver]/symphony/lib/boot/func.utilities.php:213]
    symphony_launcher();
[/[myserver]/index.php:17]
    symphony();
   `
```

**Comment by nitriques** [comment]
Ah. The default implementation of `prepareReadableValue()` does not works with array and should be implemented. Thanks for the feedback, I'll try to fix it ASAP.

**Comment by cylkee** [comment]
D'oh!  I wish I'd looked more closely at the issues.  I just stumbled on the same crash with Sym 2.6.11.  I can provide complete stack of crash if required.

**Comment by nitriques** [comment]
@cylkee Version `1.6.1` is shipped with the fix. Thanks for your patience. Please confirm that the bug is fixed!

**Comment by cylkee** [comment]
> Please confirm that the bug is fixed!

@nitriques Thanks, I've just tested in Symphony `2.6.11` with version `1.6.1` and it creates and saves okay with multiple files.  How's it looking for you @erichgoldman?

**Comment by nitriques** [comment]
@cylkee Great !
